name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4

    - name: Install ninja
      run: |
        sudo apt-get install -y ninja-build

    - name: Install gtests
      run: |
        sudo apt-get install libgtest-dev
    - name: Install nlohmann json
      run: |
        sudo apt-get install nlohmann-json3-dev
            
    - name: Install fmt
      run: |
        sudo apt-get install libfmt-dev
    
    - name: Install sdl2
      run: |
        sudo apt-get install libsdl2-dev
      
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G ninja

    - name: Build
      run: |
        ./build.sh

    - name: Test
      run: |
        ./test